phase: training
# testing
# training
# validation
phases:
  - training
  - validation
  - testing
data_path: /home/marcel/workspace/datasets/
raw_data_path: /home/marcel/workspace/datasets/raw/rosbag
exploring:
  idx: 44 #165, 377 42, 29
  frame_num: 1  #0, 1
  col: 234
explore_data_deep: True
grid_step: 16
dataset: rosbag
generator: default   # bbox, semantic, default
